sonar.projectKey=ma69158-collab_ecogrid-quality
sonar.organization=ma69158-collab
sonar.projectName=EcoGrid Quality

sonar.sources=ecogrid-quality/ecogrid
sonar.tests=ecogrid-quality/tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=ecogrid-quality/coverage.xml
